---
# tasks file for Rubrik_Cluster_Get_Failed_Jobs
- name: View the last {{ limit }} failed jobs for this RUBRIK cluster
  become: yes
  shell: sshpass -p '{{ rubrik_password }}' ssh -o StrictHostKeyChecking=no '{{ rubrik_username }}'@'{{ rubrik_host }}' "cluster get_failed_jobs --limit {{ limit }}"
  ignore_errors: true
  register: op

- set_fact:
    status_code: 2
    response_message: ".Error encountered: {{ op.stderr }}{{ op.stdout }}"
  when: op is failed
- set_fact:
    response_message: "The last 2 failed job(s) for the RUBRIK instance are as below: -\n{{ op.stdout }}{{ op.stderr }}"
  when: op is success
- debug:
    var: op
- debug:
    var: response_message

