---
# tasks file for Rubrik_Discover_Cluster
- name: Discover cluster for RUBRIK 
  become: yes
  shell: sshpass -p '{{ rubrik_password }}' ssh -o StrictHostKeyChecking=no '{{ rubrik_username }}'@'{{ rubrik_host }}' "cluster discover"
  ignore_errors: true
  register: op

- set_fact:
    status_code: 2
    response_message: "Failed to bring the support tunnel up.Error encountered: {{ op.stderr }}{{ op.stdout }}"
  when: op is failed
- set_fact:
    response_message: "Discovered the cluster for the RUBRIK instance as below: -\n{{ op.stdout }}{{ op.stderr }}"
  when: op is success
- debug:
    var: op
- debug:
    var: response_message

