---
# tasks file for Rubrik_Open_Support_Tunnel
- name: Bring up the support tunnel for {{ time_limit_in_seconds }} seconds
  become: yes
  shell: sshpass -p '{{ rubrik_password }}' ssh -o StrictHostKeyChecking=no '{{ rubrik_username }}'@'{{ rubrik_host }}' "support tunnel open {{ time_limit_in_seconds }}"
  ignore_errors: true
  register: op

- set_fact:
    status_code: 2
    response_message: "Failed to bring the support tunnel up.Error encountered: {{ op.stderr }}{{ op.stdout }}"
  when: op is failed
- set_fact:
    response_message: "{{ op.stdout }}{{ op.stderr }}"
  when: op is success
- debug: 
    var: op
- debug:
    var: response_message
